# Generated by Django 3.1.1 on 2020-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', 'CadastroP'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1),
        ),
    ]
